// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
	"printing-press-oauth2-pp-cli/internal/cliutil"
)

type Config struct {
	BaseURL            string            `toml:"base_url"`
	AuthHeaderVal      string            `toml:"auth_header"`
	Headers            map[string]string `toml:"headers,omitempty"`
	AuthSource         string            `toml:"-"`
	CredentialSource   string            `toml:"-"`
	AgentcookieManaged bool              `toml:"-"`
	AccessToken        string            `toml:"access_token"`
	RefreshToken       string            `toml:"refresh_token"`
	TokenExpiry        time.Time         `toml:"token_expiry"`
	ClientID           string            `toml:"client_id"`
	ClientSecret       string            `toml:"client_secret"`
	// TokenURL overrides the spec-baked OAuth2 token endpoint. Same fallback
	// pattern as AuthorizationURL.
	TokenURL                        string `toml:"token_url,omitempty"`
	Path                            string `toml:"-"`
	PrintingPressOauth2ClientId     string `toml:"press_oauth2_client_id"`
	PrintingPressOauth2ClientSecret string `toml:"press_oauth2_client_secret"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://api.cc.example/v1",
	}

	// Resolve config path
	path, explicitConfigFile, err := resolveConfigPath(configPath)
	if err != nil {
		return nil, err
	}
	cfg.Path = path

	// Try to load config file
	loaded := false
	if err := readConfigFile(path, cfg, "config-kind path"); err != nil {
		if !os.IsNotExist(err) {
			return nil, err
		}
	} else {
		loaded = true
	}
	if !loaded && !explicitConfigFile {
		legacyPath, err := legacyConfigPath()
		if err != nil {
			return nil, err
		}
		if legacyPath != path {
			if err := readConfigFile(legacyPath, cfg, "legacy config path"); err != nil {
				if !os.IsNotExist(err) {
					return nil, err
				}
			}
		}
	}
	cfg.Path = path
	if cfg.agentcookieManaged() {
		cfg.AgentcookieManaged = true
		cfg.CredentialSource = "agentcookie"
	} else {
		creds, ok, err := cliutil.LoadCredentials()
		if err != nil {
			return nil, err
		}
		if ok {
			cfg.clearCredentialFields()
			cfg.applyCredentials(creds)
			if cfg.hasCredentialFields() {
				cfg.AuthSource = "config"
				cfg.CredentialSource = "credentials file"
			}
		}
	}

	// Env var overrides
	if v := os.Getenv("PRINTING_PRESS_OAUTH2_CLIENT_ID"); v != "" {
		cfg.PrintingPressOauth2ClientId = v
		cfg.AuthSource = "env:PRINTING_PRESS_OAUTH2_CLIENT_ID"
		cfg.CredentialSource = "env:PRINTING_PRESS_OAUTH2_CLIENT_ID"
	}
	if v := os.Getenv("PRINTING_PRESS_OAUTH2_CLIENT_SECRET"); v != "" {
		cfg.PrintingPressOauth2ClientSecret = v
		cfg.AuthSource = "env:PRINTING_PRESS_OAUTH2_CLIENT_SECRET"
		cfg.CredentialSource = "env:PRINTING_PRESS_OAUTH2_CLIENT_SECRET"
	}
	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && cfg.hasCredentialFields() {
		cfg.AuthSource = "config"
	}
	if cfg.CredentialSource == "" && cfg.AuthSource == "config" {
		cfg.CredentialSource = "legacy config path"
	}

	// Soft agentcookie integration: if the agentcookie daemon manages this
	// CLI's secrets, it writes a marker file alongside the config file. When
	// the marker is present AND credentials came from the config (not from a
	// direct env var override that wins above), upgrade AuthSource to
	// "agentcookie" so doctor / auth-status can surface the bus state. When
	// the marker is absent, behavior is identical to pre-agentcookie: no
	// import, no network, no error. agentcookie itself is never imported
	// here — the contract is purely on-disk.
	if cfg.AuthSource == "config" {
		marker := filepath.Join(filepath.Dir(cfg.Path), ".agentcookie-managed")
		if _, err := os.Stat(marker); err == nil {
			cfg.AuthSource = "agentcookie"
			cfg.CredentialSource = "agentcookie"
			cfg.AgentcookieManaged = true
		}
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("PRINTING_PRESS_OAUTH2_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	if v := os.Getenv("PRINTING_PRESS_OAUTH2_TOKEN_URL"); v != "" {
		cfg.TokenURL = v
	}
	return cfg, nil
}

func resolveConfigPath(configPath string) (string, bool, error) {
	if strings.TrimSpace(configPath) != "" {
		return configPath, true, nil
	}
	if path := os.Getenv("PRINTING_PRESS_OAUTH2_CONFIG"); path != "" {
		return path, true, nil
	}
	dir, err := cliutil.ConfigDir()
	if err != nil {
		return "", false, err
	}
	return filepath.Join(dir, "config.toml"), false, nil
}

func legacyConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve legacy config path: %w", err)
	}
	return filepath.Join(home, ".config", "printing-press-oauth2-pp-cli", "config.toml"), nil
}

func readConfigFile(path string, cfg *Config, owner string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if err := toml.Unmarshal(data, cfg); err != nil {
		return fmt.Errorf("parsing %s %s: %w", owner, path, err)
	}
	return nil
}
func FileHasCredentialFields(path string) (bool, error) {
	var cfg Config
	if err := readConfigFile(path, &cfg, "credential probe"); err != nil {
		return false, err
	}
	return cfg.hasCredentialFields(), nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Under OAuth2 (and bearer_token specs running OAuth grants such as
	// client_credentials or device_code) the configured env vars hold flow
	// inputs, not a usable bearer; the minted AccessToken must win. Sending
	// the client_id as Authorization: Bearer surfaces as token_rejected at
	// the API.
	if c.AccessToken != "" {
		if c.AuthSource == "" || strings.HasPrefix(c.AuthSource, "env:") {
			c.AuthSource = "oauth2"
		}
		return "Bearer " + c.AccessToken
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) agentcookieManaged() bool {
	if c.AgentcookieManaged || c.AuthSource == "agentcookie" || c.CredentialSource == "agentcookie" {
		return true
	}
	if c.Path == "" {
		return false
	}
	marker := filepath.Join(filepath.Dir(c.Path), ".agentcookie-managed")
	if _, err := os.Stat(marker); err == nil {
		return true
	}
	return false
}

func (c *Config) hasCredentialFields() bool {
	if c.AuthHeaderVal != "" ||
		c.AccessToken != "" ||
		c.RefreshToken != "" ||
		!c.TokenExpiry.IsZero() ||
		c.ClientID != "" ||
		c.ClientSecret != "" {
		return true
	}
	if c.PrintingPressOauth2ClientId != "" {
		return true
	}
	if c.PrintingPressOauth2ClientSecret != "" {
		return true
	}
	return false
}

func (c *Config) clearCredentialFields() {
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	c.PrintingPressOauth2ClientId = ""
	c.PrintingPressOauth2ClientSecret = ""
}

func (c *Config) credentials() *cliutil.Credentials {
	return &cliutil.Credentials{
		AuthHeaderVal:                   c.AuthHeaderVal,
		AccessToken:                     c.AccessToken,
		RefreshToken:                    c.RefreshToken,
		TokenExpiry:                     c.TokenExpiry,
		ClientID:                        c.ClientID,
		ClientSecret:                    c.ClientSecret,
		PrintingPressOauth2ClientId:     c.PrintingPressOauth2ClientId,
		PrintingPressOauth2ClientSecret: c.PrintingPressOauth2ClientSecret,
	}
}

func (c *Config) applyCredentials(creds *cliutil.Credentials) {
	if creds == nil {
		return
	}
	c.AuthHeaderVal = creds.AuthHeaderVal
	c.AccessToken = creds.AccessToken
	c.RefreshToken = creds.RefreshToken
	c.TokenExpiry = creds.TokenExpiry
	c.ClientID = creds.ClientID
	c.ClientSecret = creds.ClientSecret
	c.PrintingPressOauth2ClientId = creds.PrintingPressOauth2ClientId
	c.PrintingPressOauth2ClientSecret = creds.PrintingPressOauth2ClientSecret
}

func (c *Config) saveCredentialsFirst() error {
	if c.agentcookieManaged() {
		c.AgentcookieManaged = true
		c.CredentialSource = "agentcookie"
		return nil
	}
	if err := cliutil.SaveCredentials(c.credentials()); err != nil {
		return err
	}
	c.CredentialSource = "credentials file"
	return nil
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	if err := c.saveCredentialsFirst(); err != nil {
		return err
	}
	return c.save()
}

func (c *Config) ClearTokens() error {
	// AuthHeader() falls back to the env-var-derived fields when AuthHeaderVal
	// and AccessToken are empty, so dropping the working credential requires
	// zeroing every emitted credential field, not just the OAuth trio.
	// ClientID/ClientSecret persist to disk via SaveTokens for the oauth2
	// and oauth2-cc flows, so logout must wipe them too; otherwise
	// `auth login` can re-mint a new access token unattended.
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	c.PrintingPressOauth2ClientId = ""
	c.PrintingPressOauth2ClientSecret = ""
	if c.agentcookieManaged() {
		c.AgentcookieManaged = true
		c.CredentialSource = "agentcookie"
		return nil
	}
	if err := cliutil.RemoveCredentials(); err != nil {
		return err
	}
	return c.save()
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	var persist any = c
	if !c.agentcookieManaged() {
		persist = c.persisted()
	}
	data, err := toml.Marshal(persist)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return atomicWriteConfigFile(c.Path, data)
}

func atomicWriteConfigFile(path string, data []byte) error {
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, data, 0o600); err != nil {
		return fmt.Errorf("writing temporary config: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("publishing config: %w", err)
	}
	return nil
}

type persistedConfig struct {
	BaseURL  string            `toml:"base_url"`
	Headers  map[string]string `toml:"headers,omitempty"`
	TokenURL string            `toml:"token_url,omitempty"`
}

func (c *Config) persisted() persistedConfig {
	return persistedConfig{
		BaseURL:  c.BaseURL,
		Headers:  c.Headers,
		TokenURL: c.TokenURL,
	}
}

// Ensure strings import is used
var _ = strings.ReplaceAll
